### ISSUE TITLE
Record 2 More Takes of Lightning Solo

### ISSUE THREAD

**Issue by sethcenterbar** [sethcenterbar/SwelterSounds#9]
The solo sounds pretty good, but I'd like to be able to comp a few takes to get it to really vibe. If you could do two more tracks of it (or more), I think we can really make it smack.

**Comment by ajhirsch93** [comment]
did 5 takes. here is the drive link https://drive.google.com/file/d/1tayYsn6wDvoemr2OWbiWGSnzqgOkRuy0/view?usp=sharing
